import React from 'react'
import CertainDashboard from './Reusable/CertainDashboard'
import CardedChart from './Reusable/CardedChart'

const AIDriven = () => {
    const textListCustomization = {
        chartType: "textList",
        textItems: [
            "AI predicts a 40% rise in demand for anti-viral drugs in the next quarter.",
            "Machine learning model detects a potential supply chain disruption in raw materials for vaccines.",
            "Deep learning analysis suggests early signs of adverse reactions in new diabetes medication.",
            "AI-driven risk model forecasts increased scrutiny on opioid prescriptions in 2025.",
            "Predictive analytics identify a 30% reduction in antibiotic efficacy due to rising resistance.",
            "AI recommendation: Shift 20% of production to alternative supply hubs to prevent shortages.",
            "Real-time NLP models detect a surge in negative patient sentiment regarding a newly launched drug.",
            "AI flags inconsistencies in clinical trial data, recommending additional review.",
        ],
    };
    
    return (
        <div>
            <CertainDashboard title="AI-Driven Actionable Insights & Recommendations">
                <></>
                <CardedChart chartHeading="Predictive Insights (Auto-generated by AI)" chartCustomization={textListCustomization} />  
            </CertainDashboard>
        </div>
    )
}

export default AIDriven